from itertools import cycle

bot_servers = []
invite_cache = {}
member_counters = {}
custom_role_counters = {}
role_counters = {}
active_ticket_counters = {}
resolved_ticket_counters = {}
chatbot_history = {}
sniped = {}
afk = {}
raided = {}
reminders = {}
interaction_cooldowns = {}
timed_close_tickets = {}
blacklist = []
blacklist_guilds = []
warning_emoji = "<:Warning:1247220837791043585>"
success_emoji = "<:Success:1247235841609175170>"
error_emoji = "<:Error:1247220752340488272>"

COUNTRIES = [
"Afghanistan", 
"Albania", 
"Algeria", 
"Andorra", 
"Argentina",
"Australia", 
"Austria", 
"Bolivia", 
"Belarus", 
"Belgium",
"Botswana",
"Brazil",
"Cambodia",
"Bulgaria",
"Canada", 
"Chile", 
"China", 
"Colombia",
"Costa Rica", 
"Croatia", 
"Cyprus", 
"Czech Republic",
"Denmark", 
"Dominican Republic", 
"Ecuador",
"Egypt",
"Estonia", 
"Finland", 
"France",
"Gambia",
"Georgia", 
"Germany", 
"Greece", 
"Guatemala", 
"Hong Kong", 
"Hungary", 
"Iceland", 
"India", 
"Indonesia", 
"Ireland", 
"Israel", 
"Italy", 
"Japan",
"Kenya",
"Jordan",
"Latvia",
"Kazakhstan", 
"Kuwait", 
"Lithuania",
"Luxembourg",
"Macedonia",
"Malaysia",
"Mexico",
"Monaco",
"North Macedonia",
"Nigeria",
"Morocco", 
"Netherland Antilles", 
"Netherlands", 
"New Zealand",
"Nicaragua",
"Norway",
"Oman",
"Pakistan", 
"Panama",
"Paraguay",
"Peru", 
"Philippines", 
"Poland", 
"Portugal", 
"Qatar", 
"Romania", 
"Russia", 
"Saudi Arabia",
"Senegal",
"Serbia", 
"Singapore", 
"Slovakia", 
"Slovenia", 
"South Africa", 
"Spain",
"Sri Lanka",
"Sweden", 
"Switzerland", 
"Taiwan", 
"Thailand", 
"Turkey", 
"Ukraine", 
"United Arab Emirates", 
"United Kingdom",
"United States of America",
"Uruguay", 
"Vietnam",
"Zambia"
]

hangman_words = [
    "hangman", "apple", "banana", "cherry", "orange", "grape", "mango", "strawberry", "peach", "melon",
    "lemon", "blueberry", "blackberry", "pineapple", "coconut", "watermelon", "papaya", "kiwi", "pear",
    "plum", "mushroom", "potato", "carrot", "lettuce", "cabbage", "broccoli", "cauliflower", "cucumber",
    "eggplant", "garlic", "ginger", "pepper", "radish", "spinach", "tomato", "avocado", "bean", "corn",
    "onion", "pea", "rice", "wheat", "barley", "oats", "lentil", "chicken", "beef", "pork", "bacon",
    "sausage", "ham", "turkey", "duck", "lamb", "goat", "fish", "shrimp", "lobster", "crab", "oyster",
    "mussel", "clam", "squid", "octopus", "snail", "scallop", "bread", "biscuit", "croissant", "pancake",
    "waffle", "bagel", "muffin", "doughnut", "pie", "cake", "cookie", "brownie", "candy",
    "chocolate", "toffee", "fudge", "caramel", "marshmallow", "jelly", "jam", "honey", "syrup", "rice",
    "spaghetti", "macaroni", "lasagna", "noodle", "taco", "burrito", "sandwich", "hamburger",
    "hotdog", "fries", "soup", "salad", "stew", "curry", "chowder", "stirfry", "goulash", "kebab",
    "pilaf", "couscous", "paella", "sushi", "sashimi", "udon", "tempura", "teriyaki", "sukiyaki", "ramen",
    "meatloaf", "enchiladas", "quesadilla", "salsa", "guacamole", "margarita", "mojito",
    "martini", "mimosa", "whiskey", "vodka", "rum", "tequila", "brandy", "gin", "scotch", "wine", "beer",
    "cider", "ale", "lager", "pilsner", "stout", "porter", "chardonnay", "pinot", "merlot", "riesling",
    "cabernet", "syrah", "malbec", "grenache", "rose", "chablis", "sauvignon", "vermouth", "chard", "bubbly",
    "carmenere", "beverage", "juice", "coffee", "tea", "latte", "cappuccino", "espresso", "americano",
    "mocha", "smoothie", "lemonade", "cola", "soda", "sprite", "gingerale", "rootbeer", "pepsi", "coke",
    "mountaindew", "snapple", "icedtea", "peachtea", "applecider", "milk", "soyamilk", "almondmilk", "coconutmilk",
    "oatmilk", "eggnog", "gatorade", "powerrade", "redbull", "monster", "rockstar", "cocoa", "frappuccino", 
    "cap", "macchiato", "cortado", "caramelmacchiato", "brew", "icedcoffee", "coldbrew", "icedlatte", "icedmocha", 
    "hotchocolate", "trinity", "mcdonalds", "burgerking", "wendys", "tacobell", "kfc", "dominos",
    "lambo", "ferrari", "porsche", "bugatti", "tesla", "mercedes", "bmw", "audi", "volkswagen", "honda", "toyota",
    "nike", "adidas", "puma", "reebok", "underarmour", "gucci", "louisvuitton", "chanel", "prada", "versace",
    "iron man", "captain america", "thor", "hulk", "black widow", "hawkeye", "spiderman",
    "computer", "laptop", "mouse", "keyboard", "monitor", "printer", "scanner", "speakers", "headphones"
    ]

eight_ball_answers = [
    "It is certain.",
    "It is decidedly so.",
    "Without a doubt.",
    "Yes - definitely.",
    "You may rely on it.",
    "As I see it, yes.",
    "Most likely.",
    "Outlook good.",
    "Yes.",
    "Signs point to yes.",
    "Don't count on it.",
    "My reply is no.",
    "My sources say no...",
    "Outlook not so good.",
    "Very doubtful."
]

dares = [
    "Do a cartwheel in the nearest open space.",
    "Sing a song in front of everyone.",
    "Do a funny dance for 1 minute.",
    "Speak in a foreign accent for the next 3 rounds.",
    "Go outside and shout 'I love Python' as loud as you can.",
    "Text your crush 'I like you' right now.",
    "Talk to a stranger for 5 minutes.",
    "Give a 2-minute speech on why pizza is overrated.",
    "Do 20 push-ups right now.",
    "Take a selfie with a funny face and post it in the server.",
    "Go to the nearest store and ask for a job application form.",
    "Call a friend and sing 'Happy Birthday' to them, even if it's not their birthday.",
    "Wear your clothes backward for the next 2 rounds.",
    "Send a random meme to the last person you texted.",
    "Do a plank for as long as you can hold it.",
    "Do a handstand against the nearest wall for 30 seconds.",
    "Text your parents 'I broke something, but it's not a big deal.'",
    "Do a catwalk in the room.",
    "Let someone else style your hair any way they want.",
    "Do 10 jumping jacks right now.",
    "Do an impression of your favorite celebrity.",
    "Put on a blindfold and attempt to do a cartwheel.",
    "Speak in slow motion for the next 5 minutes.",
    "Tell a funny joke to the server.",
    "Draw a caricature of one of the server members.",
    "Wear your socks on your hands for the next 3 rounds.",
    "Take a cold shower right now.",
    "Balance a spoon on your nose for 1 minute.",
    "Attempt to breakdance for 1 minute.",
    "Do a yoga pose of the group's choice.",
    "Call a family member and sing them a nursery rhyme.",
    "Give a piggyback ride to someone in the group.",
    "Send a text to your ex saying 'I miss you'.",
    "Put on lipstick as a guy and leave it on for the next 3 rounds.",
    "Make a funny face and have everyone take a picture.",
    "Try to juggle three different items in the room.",
    "Give a high-five to a stranger outside.",
    "Do a somersault right now.",
    "Talk about a weird dream you've had in vivid detail.",
    "Do the chicken dance for 2 minutes straight.",
    "Give a 1-minute stand-up comedy routine.",
    "Try to lick your elbow for 30 seconds.",
    "Do 5 burpees right now.",
    "Do a rap freestyle about a random object in the room.",
    "Let someone tickle you for 1 minute.",
    "Speak with your tongue out for the next 3 rounds.",
    "Give a foot massage to someone in the group.",
    "Go outside and do 10 jumping jacks while shouting your favorite food.",
    "Wear your pants backward for the next 2 rounds.",
    "Draw a mustache on your face using a marker.",
    "Do the floss dance for 1 minute straight.",
    "Try to break an awkward dance move and hold it for 30 seconds.",
    "Give a back massage to someone in the group.",
    "Balance a book on your head and walk across the room.",
    "Speak in a high-pitched voice for the next 5 minutes.",
    "Do 20 squats right now."
]

truths = [
    "What is your biggest fear?",
    "What is your most embarrassing childhood memory?",
    "What is your biggest regret in life so far?",
    "What is the one thing you can't live without?",
    "What is your biggest pet peeve?",
    "What is your most embarrassing moment in public?",
    "What is the one thing you wish you could change about yourself?",
    "What is your favorite guilty pleasure?",
    "What is the most adventurous thing you've ever done?",
    "What is your most irrational fear?",
    "What is the craziest thing you've done for love?",
    "What is your biggest dream in life?",
    "What is the most childish thing you still love to do?",
    "What is the one secret you've never told anyone?",
    "What is the most embarrassing thing your parents have caught you doing?",
    "What is the one thing you would do if you knew you couldn't fail?",
    "What is the most trouble you've ever gotten into?",
    "What is the one thing you would change about your family?",
    "What is the most spontaneous thing you've ever done?",
    "What is the most ridiculous thing you've ever bought?",
    "What is your biggest accomplishment in life so far?",
    "What is the one thing you would do if you were invisible for a day?",
    "What is your most awkward date experience?",
    "What is your greatest phobia?",
    "What is your most embarrassing nickname?",
    "What is your greatest extravagance?",
    "What is the craziest thing you've ever eaten?",
    "What is the one thing you wish you were better at?",
    "What is the most challenging thing you've had to overcome?",
    "What is the most ridiculous rumor you've ever heard about yourself?",
    "What is your favorite way to relax after a long day?",
    "What is the one thing you wish everyone knew about you?",
    "What is the most spontaneous trip you've ever taken?",
    "What is the one thing you're too scared to try?",
    "What is the most embarrassing thing you've Googled?",
    "What is your most annoying habit?",
    "What is the most valuable lesson you've learned from a past relationship?",
    "What is the one thing you would change about your past if you could?",
    "What is the most unusual thing you're afraid of?",
    "What is the biggest lie you've ever told?",
    "What is the one thing you're most proud of but never get to talk about?",
    "What is the most meaningful compliment you've ever received?",
    "What is the biggest misconception people have about you?",
    "What is your greatest unfulfilled ambition?",
    "What is the most rebellious thing you did as a teenager?",
    "What is the one thing you would change about your current job?",
    "What is the biggest lie you've ever told your best friend?",
    "What is your greatest insecurity?",
    "What is the most valuable lesson you've learned from a failure?",
    "What is the one thing you're afraid to ask for, but want the most?",
    "What is the most significant turning point in your life so far?",
    "What is the one thing you wish you could apologize for?",
    "What is the most adventurous thing you've ever wanted to try but haven't?",
    "What is the one thing you admire most about yourself?",
    "What is the most impactful piece of advice you've ever received?",
    "What is your ultimate goal in life?",
    "What is the one thing you would change about your personality?",
    "What is the most memorable dream you've ever had?",
    "What is the most important lesson you've learned from your parents?",
    "What is the biggest misconception you think people have about love?"
]

hugs = cycle([
    "https://media.giphy.com/media/3ZnBrkqoaI2hq/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExajd4ZDRnOTk4am95NzFhMW9sdHFoNHV4bTdjM3hxajk1bGc3ZWh4NiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5OqXb948EBkyUcnwHt/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaTUyNTNiOW11NWh1czE2c2RsbXVjcW96bWg3b3YyeWExa2czOTZmNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/9d3LQ6TdV2Flo8ODTU/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExczkzOHA2MGcwdWt6cm1vZDhsZmNiYXJxdGFzY2x5bXB6eDZ1djh6YyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/VhRU9RvKZWKujYXhlJ/giphy.gif"
])

kisses = cycle([
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExaDNxb2Vydmh6MHFyanBibmdwdXBiY2JneHpmeGxua3BwNWw3OHN2aiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xUOwG290r6jsP9GG40/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdXg3cTNpOHZzMHYzejN5bzRxbnBhdDd4dW5ocnB3NXNheXV4YjltbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/JC5fPiCywwJSG1zLbe/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjA1cXl6M3kxaTZhNDJiYTVtYW0wbjljZ3J1a2luMDQ1bzdybXRsYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/no7LLgLFHBr09R2atx/giphy.gif"
])

pats = cycle([
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnJjMW40Yjh4MWRmdnB6amdic2sxeWJvaWUxbW1ybG5tbTBvb25vbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xUA7bahIfcCqC7S4qA/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExeWJrZ2N2bHF0cnM3aWVxejJ0ODQ4eDc1dnB1cnI2aGxhcWdsZDRwMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3oFzmm13V0h44D61bi/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcWY0c2d1ZjZqbDd0MTN6M2F1cnpiZ2ZldXA2M3RvbWYxcnk1ZmplbiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/M0TtMBYmOySimtbO44/giphy.gif",
    "api"
])

slaps = cycle([
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ3F4bjN6MTVncDM3eDN6NndmYmd3OHk2anF4OXcwdnNibjR0MGk2ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qyjexFwQwJp9yUvMxq/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZzhibjBqdDVybWprcDM4eTFsaGc5dTc5ZWIzbXl1NmkxZ3U5Y3d0YyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3XlEk2RxPS1m8/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZGFmd215cmhwd3hyY3BuaG96czU4cTV5N2RmZ2Q1bXFncXpmMWQxMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Qumf2QovTD4QxHPjy5/giphy.gif",
    "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYXkwM2owMDloZnViaHBrbWk4MHAwOGdhenkxbTU2OXhpNm53aGs3NCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/uqSU9IEYEKAbS/giphy.gif"
])

user_permission_names = {
    "moderate_members": "Moderate Members",
    "use_voice_activation": "Voice Activation",
    "view_channel": "View Channels",
    "external_stickers": "Use External Stickers",
    "create_instant_invite": "Create Instant Invite",
    "kick_members": "Kick Members",
    "ban_members": "Ban Members",
    "administrator": "Administrator",
    "manage_channels": "Manage Channels",
    "manage_guild": "Manage Server",
    "add_reactions": "Add Reactions",
    "view_audit_log": "View Audit Log",
    "priority_speaker": "Priority Speaker",
    "stream": "Stream",
    "read_messages": "Read Messages",
    "send_messages": "Send Messages",
    "send_tts_messages": "Send TTS Messages",
    "manage_messages": "Manage Messages",
    "embed_links": "Embed Links",
    "attach_files": "Attach Files",
    "read_message_history": "Read Message History",
    "mention_everyone": "Mention Everyone",
    "external_emojis": "Use External Emojis",
    "connect": "Connect (Voice)",
    "speak": "Speak (Voice)",
    "mute_members": "Mute Members (Voice)",
    "deafen_members": "Deafen Members (Voice)",
    "move_members": "Move Members (Voice)",
    "use_voice_activity": "Use Voice Activity (Voice)",
    "change_nickname": "Change Nickname",
    "manage_nicknames": "Manage Nicknames",
    "manage_roles": "Manage Roles",
    "manage_webhooks": "Manage Webhooks",
    "manage_emojis": "Manage Emojis",
    "use_slash_commands": "Use Slash Commands",
    "request_to_speak": "Request to Speak (Voice)",
    "manage_threads": "Manage Threads",
    "use_thread": "Use Threads",
    "create_public_thread": "Create Public Threads",
    "create_private_thread": "Create Private Threads",
    "use_external_stickers": "Use External Stickers",
    "send_messages_in_threads": "Send Messages in Threads",
    "start_embedded_activities": "Start Embedded Activities",
    "use_application_commands": "Use Application Commands",
    "manage_thread_invites": "Manage Thread Invites",
    "use_vad": "Use Voice Activity (Voice)",
    "connect_to_vc": "Connect to Voice Channel",
    "speak_in_vc": "Speak in Voice Channel",
    "mute_members_in_vc": "Mute Members in Voice Channel",
    "deafen_members_in_vc": "Deafen Members in Voice Channel",
    "move_members_in_vc": "Move Members in Voice Channel",
    "use_vad_in_vc": "Use Voice Activity in Voice Channel",
    "priority_speaker_in_vc": "Priority Speaker in Voice Channel",
    "stream_in_vc": "Stream in Voice Channel",
    "create_private_threads": "Create Private Threads",
    "create_public_threads": "Create Public Threads"}

role_permission_names = {
    "moderate_members": "Moderate Members",
    "use_voice_activation": "Voice Activation",
    "view_channel": "View Channels",
    "external_stickers": "Use External Stickers",
    "create_instant_invite": "Create Instant Invite",
    "kick_members": "Kick Members",
    "ban_members": "Ban Members",
    "administrator": "Administrator",
    "manage_channels": "Manage Channels",
    "manage_guild": "Manage Server",
    "add_reactions": "Add Reactions",
    "view_audit_log": "View Audit Log",
    "priority_speaker": "Priority Speaker",
    "stream": "Stream",
    "read_messages": "Read Messages",
    "send_messages": "Send Messages",
    "send_tts_messages": "Send TTS Messages",
    "manage_messages": "Manage Messages",
    "embed_links": "Embed Links",
    "attach_files": "Attach Files",
    "read_message_history": "Read Message History",
    "mention_everyone": "Mention Everyone",
    "external_emojis": "Use External Emojis",
    "connect": "Connect (Voice)",
    "speak": "Speak (Voice)",
    "mute_members": "Mute Members (Voice)",
    "deafen_members": "Deafen Members (Voice)",
    "move_members": "Move Members (Voice)",
    "use_voice_activity": "Use Voice Activity (Voice)",
    "change_nickname": "Change Nickname",
    "manage_nicknames": "Manage Nicknames",
    "manage_roles": "Manage Roles",
    "manage_webhooks": "Manage Webhooks",
    "manage_emojis": "Manage Emojis",
    "use_slash_commands": "Use Slash Commands",
    "request_to_speak": "Request to Speak (Voice)",
    "manage_threads": "Manage Threads",
    "use_thread": "Use Threads",
    "create_public_thread": "Create Public Threads",
    "create_private_thread": "Create Private Threads",
    "use_external_stickers": "Use External Stickers",
    "send_messages_in_threads": "Send Messages in Threads",
    "start_embedded_activities": "Start Embedded Activities",
    "use_application_commands": "Use Application Commands",
    "manage_thread_invites": "Manage Thread Invites",
    "use_vad": "Use Voice Activity (Voice)",
    "connect_to_vc": "Connect to Voice Channel",
    "speak_in_vc": "Speak in Voice Channel",
    "mute_members_in_vc": "Mute Members in Voice Channel",
    "deafen_members_in_vc": "Deafen Members in Voice Channel",
    "move_members_in_vc": "Move Members in Voice Channel",
    "use_vad_in_vc": "Use Voice Activity in Voice Channel",
    "priority_speaker_in_vc": "Priority Speaker in Voice Channel",
    "stream_in_vc": "Stream in Voice Channel",
    "create_private_threads": "Create Private Threads",
    "create_public_threads": "Create Public Threads"}

channel_permission_names = {
    "moderate_members": "Moderate Members",
    "use_voice_activation": "Voice Activation",
    "view_channel": "View Channels",
    "external_stickers": "Use External Stickers",
    "create_instant_invite": "Create Instant Invite",
    "kick_members": "Kick Members",
    "ban_members": "Ban Members",
    "view_channel": "View Channel",
    "administrator": "Administrator",
    "manage_channels": "Manage Channels",
    "manage_guild": "Manage Server",
    "add_reactions": "Add Reactions",
    "view_audit_log": "View Audit Log",
    "priority_speaker": "Priority Speaker",
    "stream": "Stream",
    "read_messages": "Read Messages",
    "send_messages": "Send Messages",
    "send_tts_messages": "Send TTS Messages",
    "manage_messages": "Manage Messages",
    "embed_links": "Embed Links",
    "attach_files": "Attach Files",
    "read_message_history": "Read Message History",
    "mention_everyone": "Mention Everyone",
    "external_emojis": "Use External Emojis",
    "connect": "Connect (Voice)",
    "speak": "Speak (Voice)",
    "mute_members": "Mute Members (Voice)",
    "deafen_members": "Deafen Members (Voice)",
    "move_members": "Move Members (Voice)",
    "use_voice_activity": "Use Voice Activity (Voice)",
    "change_nickname": "Change Nickname",
    "manage_nicknames": "Manage Nicknames",
    "manage_roles": "Manage Roles",
    "manage_webhooks": "Manage Webhooks",
    "manage_emojis": "Manage Emojis",
    "use_slash_commands": "Use Slash Commands",
    "request_to_speak": "Request to Speak (Voice)",
    "manage_threads": "Manage Threads",
    "use_thread": "Use Threads",
    "create_public_thread": "Create Public Threads",
    "create_private_thread": "Create Private Threads",
    "use_external_stickers": "Use External Stickers",
    "send_messages_in_threads": "Send Messages in Threads",
    "start_embedded_activities": "Start Embedded Activities",
    "use_application_commands": "Use Application Commands",
    "manage_thread_invites": "Manage Thread Invites",
    "use_vad": "Use Voice Activity (Voice)",
    "connect_to_vc": "Connect to Voice Channel",
    "speak_in_vc": "Speak in Voice Channel",
    "mute_members_in_vc": "Mute Members in Voice Channel",
    "deafen_members_in_vc": "Deafen Members in Voice Channel",
    "move_members_in_vc": "Move Members in Voice Channel",
    "use_vad_in_vc": "Use Voice Activity in Voice Channel",
    "priority_speaker_in_vc": "Priority Speaker in Voice Channel",
    "stream_in_vc": "Stream in Voice Channel",
    "create_private_threads": "Create Private Threads",
    "create_public_threads": "Create Public Threads"}

badge_names = {
    "staff": "Staff",
    "partner": "Partner",
    "hypesquad": "HypeSquad Events",
    "bug_hunter": "Bug Hunter",
    "hypesquad_bravery": "HypeSquad Bravery",
    "hypesquad_brilliance": "HypeSquad Brilliance",
    "hypesquad_balance": "HypeSquad Balance",
    "early_supporter": "Early Supporter",
    "team_user": "Team User",
    "system": "System",
    "bug_hunter_level_2": "Bug Hunter Level 2",
    "verified_bot": "Verified Bot",
    "verified_bot_developer": "Verified Bot Developer",
    "active_developer": "Active Developer"}

status_names = {
    "online": "Online",
    "dnd": "Do Not Disturb",
    "idle": "Idle",
    "offline": "Offline"}

elements = [
    "Hydrogen",
    "Helium",
    "Lithium",
    "Beryllium",
    "Boron",
    "Carbon",
    "Nitrogen",
    "Oxygen",
    "Fluorine",
    "Neon",
    "Sodium",
    "Magnesium",
    "Aluminum",
    "Silicon",
    "Phosphorus",
    "Sulfur",
    "Chlorine",
    "Argon",
    "Potassium",
    "Calcium",
    "Scandium",
    "Titanium",
    "Vanadium",
    "Chromium",
    "Manganese",
    "Iron",
    "Cobalt",
    "Nickel",
    "Copper",
    "Zinc",
    "Gallium",
    "Germanium",
    "Arsenic",
    "Selenium",
    "Bromine",
    "Krypton",
    "Rubidium",
    "Strontium",
    "Yttrium",
    "Zirconium",
    "Niobium",
    "Molybdenum",
    "Technetium",
    "Ruthenium",
    "Rhodium",
    "Palladium",
    "Silver",
    "Cadmium",
    "Indium",
    "Tin",
    "Antimony",
    "Tellurium",
    "Iodine",
    "Xenon",
    "Cesium",
    "Barium",
    "Lanthanum",
    "Cerium",
    "Praseodymium",
    "Neodymium",
    "Promethium",
    "Samarium",
    "Europium",
    "Gadolinium",
    "Terbium",
    "Dysprosium",
    "Holmium",
    "Erbium",
    "Thulium",
    "Ytterbium",
    "Lutetium",
    "Hafnium",
    "Tantalum",
    "Tungsten",
    "Rhenium",
    "Osmium",
    "Iridium",
    "Platinum",
    "Gold",
    "Mercury",
    "Thallium",
    "Lead",
    "Bismuth",
    "Polonium",
    "Astatine",
    "Radon",
    "Francium",
    "Radium",
    "Actinium",
    "Thorium",
    "Protactinium",
    "Uranium",
    "Neptunium",
    "Plutonium",
    "Americium",
    "Curium",
    "Berkelium",
    "Californium",
    "Einsteinium",
    "Fermium",
    "Mendelevium",
    "Nobelium",
    "Lawrencium",
    "Rutherfordium",
    "Dubnium",
    "Seaborgium",
    "Bohrium",
    "Hassium",
    "Meitnerium",
    "Darmstadtium",
    "Roentgenium",
    "Copernicium",
    "Nihonium",
    "Flerovium",
    "Moscovium",
    "Livermorium",
    "Tennessine",
    "Oganesson"
]

major_cities = [
    "Abu Dhabi",
    "Accra",
    "Addis Ababa",
    "Algiers",
    "Amman",
    "Amsterdam",
    "Ankara",
    "Antananarivo",
    "Apia",
    "Ashgabat",
    "Asmara",
    "Astana",
    "Athens",
    "Baku",
    "Bamako",
    "Bangkok",
    "Bangui",
    "Banjul",
    "Basseterre",
    "Beijing",
    "Beirut",
    "Belgrade",
    "Belmopan",
    "Berlin",
    "Bern",
    "Bishkek",
    "Bissau",
    "Bogota",
    "Brasilia",
    "Bratislava",
    "Brazzaville",
    "Bridgetown",
    "Brussels",
    "Bucharest",
    "Budapest",
    "Bujumbura",
    "Cairo",
    "Canberra",
    "Caracas",
    "Castries",
    "Chisinau",
    "Conakry",
    "Copenhagen",
    "Dakar",
    "Damascus",
    "Dhaka",
    "Djibouti",
    "Dodoma",
    "Doha",
    "Dublin",
    "Dushanbe",
    "Freetown",
    "Gaborone",
    "Georgetown",
    "Hanoi",
    "Harare",
    "Havana",
    "Helsinki",
    "Islamabad",
    "Jakarta",
    "Juba",
    "Kabul",
    "Kampala",
    "Kathmandu",
    "Khartoum",
    "Kiev",
    "Kigali",
    "Kingston",
    "Kingstown",
    "Kinshasa",
    "Kuala Lumpur",
    "Kuwait City",
    "Libreville",
    "Lilongwe",
    "Lima",
    "Lisbon",
    "Ljubljana",
    "Lome",
    "London",
    "Luanda",
    "Lusaka",
    "Luxembourg",
    "Madrid",
    "Majuro",
    "Malabo",
    "Male",
    "Managua",
    "Manama",
    "Manila",
    "Maputo",
    "Maseru",
    "Mbabane",
    "Melekeok",
    "Mexico City",
    "Minsk",
    "Mogadishu",
    "Monaco",
    "Monrovia",
    "Montevideo",
    "Moroni",
    "Moscow",
    "Muscat",
    "Nairobi",
    "Nassau",
    "Naypyidaw",
    "N'Djamena",
    "New Delhi",
    "Niamey",
    "Nicosia",
    "Nouakchott",
    "Nuku'alofa",
    "Oslo",
    "Ottawa",
    "Ouagadougou",
    "Panama City",
    "Paramaribo",
    "Paris",
    "Phnom Penh",
    "Podgorica",
    "Port Louis",
    "Port Moresby",
    "Port-au-Prince",
    "Porto-Novo",
    "Prague",
    "Praia",
    "Pretoria",
    "Pyongyang",
    "Quito",
    "Rabat",
    "Reykjavik",
    "Riga",
    "Riyadh",
    "Rome",
    "Roseau",
    "Saint George's",
    "San Jose",
    "San Marino",
    "San Salvador",
    "Sanaa",
    "Santiago",
    "Santo Domingo",
    "Sarajevo",
    "Seoul",
    "Singapore",
    "Skopje",
    "Sofia",
    "Stockholm",
    "Suva",
    "Tallinn",
    "Tashkent",
    "Tbilisi",
    "Tegucigalpa",
    "Tehran",
    "Thimphu",
    "Tirana",
    "Tokyo",
    "Tripoli",
    "Tunis",
    "Ulaanbaatar",
    "Vaduz",
    "Valletta",
    "Vatican City",
    "Vienna",
    "Vientiane",
    "Vilnius",
    "Warsaw",
    "Washington, D.C.",
    "Wellington",
    "Windhoek",
    "Yaounde",
    "Yerevan",
    "Zagreb",
]

languages = [
    "English",
    "Spanish",
    "Hindi",
    "Arabic",
    "Bengali",
    "Portuguese",
    "Russian",
    "Japanese",
    "Punjabi",
    "German",
    "Javanese",
    "Telugu",
    "Marathi",
    "Turkish",
    "Korean",
    "French",
    "Vietnamese",
    "Tamil",
    "Italian",
    "Urdu",
    "Persian",
    "Polish",
    "Malayalam",
    "Burmese",
    "Yoruba",
    "Swahili",
    "Thai",
    "Ukrainian",
    "Romanian",
    "Malay",
    "Sindhi",
    "Farsi",
    "Hausa",
    "Dutch",
    "Pashto",
    "Kannada",
    "Odia",
    "Filipino",
    "Amharic",
    "Serbo-Croatian",
    "Maithili",
    "Sundanese",
    "Nepali",
    "Sinhala",
    "Chhattisgarhi",
    "Hmong",
    "Somali",
    "Khmer",
    "Assamese",
    "Madurese",
    "Marwari",
    "Saraiki",
    "Cebuano",
    "Nepal Bhasa",
    "Rajasthani",
    "Saraiki",
    "Kurdish",
    "Malagasy",
    "Kazakh",
    "Luxembourgish",
    "Esperanto",
    "Tatar",
    "Uighur",
    "Welsh",
    "Scottish Gaelic",
    "Irish",
    "Basque",
    "Galician",
    "Icelandic",
    "Frisian",
    "Faroese",
    "Hawaiian",
    "Samoan",
    "Tongan",
    "Fijian",
    "Maori",
    "Sesotho",
    "Zulu",
    "Maltese",
    "Azerbaijani",
    "Armenian",
    "Lao",
    "Yiddish",
]

wyr_questions = [
    "Would you rather have the ability to fly or be invisible?",
    "Would you rather eat pizza every day or never eat pizza again?",
    "Would you rather travel to the past or the future?",
    "Would you rather have the ability to teleport anywhere or read minds?",
    "Would you rather live in a world with no internet or no cell phones?",
    "Would you rather be a famous actor or a successful entrepreneur?",
    "Would you rather have a pet dragon or be able to breathe underwater?",
    "Would you rather always speak your mind or never speak again?",
    "Would you rather be a superhero with no secret identity or a supervillain with a hidden agenda?",
    "Would you rather have a time machine that only goes to the past or one that only goes to the future?",
    "Would you rather have the power of super strength or the power of invisibility?",
    "Would you rather be a famous musician or a renowned artist?",
    "Would you rather have the ability to control the weather or control time?",
    "Would you rather always have to sing instead of speaking or dance everywhere you go?",
    "Would you rather have the power to fly but never be able to land or have the ability to turn invisible but only when no one is looking?",
    "Would you rather live in a world without music or a world without movies?",
    "Would you rather eat only pizza for the rest of your life or never eat pizza again?",
    "Would you rather be able to speak all languages fluently or play all musical instruments perfectly?",
    "Would you rather have the ability to time travel but not control where you end up or be able to teleport but only to places you've already visited?",
    "Would you rather always know the truth but never be able to lie or always be able to lie but never know the truth?",
    "Would you rather have a personal chef or a personal chauffeur?",
    "Would you rather be a famous actor/actress in a bad movie or an unknown actor/actress in a critically acclaimed movie?",
    "Would you rather have the power to control fire or control water?",
    "Would you rather be a character in your favorite video game or a character in your favorite book?",
    "Would you rather be able to communicate with animals or speak all human languages?",
    "Would you rather have the ability to instantly learn any new skill or have unlimited wealth?",
    "Would you rather have the power of super speed or the ability to teleport short distances?",
    "Would you rather go back in time and meet your ancestors or go into the future and meet your descendants?",
    "Would you rather never feel physical pain or never feel emotional pain?",
    "Would you rather always have to whisper or always have to shout when you speak?",
    "Would you rather have the ability to change the past or see into the future, but only once?",
    "Would you rather be able to breathe underwater but never swim on the surface or be able to fly but never land?",
    "Would you rather have the power to instantly learn any language or play any musical instrument perfectly?",
    "Would you rather have the ability to teleport anywhere in the world but not control where you end up or be able to time travel but not control when you go?",
    "Would you rather always feel too hot or always feel too cold?",
    "Would you rather have a job you love with a low salary or a job you hate with a high salary?",
    "Would you rather be able to speak with animals or understand any foreign language instantly?",
    "Would you rather be famous for something you didn't do or be a hero for something you didn't want to do?",
    "Would you rather always know the answer to any question but never be able to ask questions or always have questions but never know the answers?",
    "Would you rather have the ability to speak with animals or understand any language spoken by humans?",
    "Would you rather be able to stop time for 10 seconds once a day or rewind time by 10 seconds once a day?",
    "Would you rather always be 10 minutes late or always be 20 minutes early?",
    "Would you rather have a rewind button for your life or a pause button?",
    "Would you rather live in a world where there is no war but no technological advancements or a world with advanced technology but constant conflict?",
    "Would you rather have the power to heal any illness or have the power to prevent accidents?",
    "Would you rather always have to tell the truth or always tell convincing lies?",
    "Would you rather be able to communicate with plants or with machines?",
    "Would you rather have the ability to predict the future or change the past?",
    "Would you rather never have to sleep but still feel rested or sleep as much as you want without ever feeling tired?",
    "Would you rather live in a treehouse in a forest or a cabin by the beach?",
    "Would you rather always have perfect weather for outdoor activities or have the ability to control the weather for everyone?",
    "Would you rather have a personal chef or a personal trainer?",
    "Would you rather discover a hidden treasure or solve a long-standing mystery?",
    "Would you rather have the ability to speak all languages fluently or be a master of all musical instruments?",
    "Would you rather be a famous actor in a terrible movie or an unknown actor in an Oscar-winning film?",
    "Would you rather be the funniest person in the room or the smartest?",
    "Would you rather have the power to instantly learn any skill or have unlimited resources to pursue any hobby?",
    "Would you rather live in a world without books or without music?",
    "Would you rather be able to control fire or control water?",
    "Would you rather have a job you love but low pay or a job you dislike but a high salary?",
    "Would you rather have the ability to teleport anywhere instantly or have the power of invisibility?",
    "Would you rather experience the beginning of the universe or the end of it?",
    "Would you rather be a famous painter or a renowned author?",
    "Would you rather be able to fly but only at walking speed or run as fast as a car?",
    "Would you rather have a personal robot assistant or a personal holographic assistant?",
    "Would you rather have the power to heal physical wounds or heal emotional pain?",
    "Would you rather have the ability to instantly know any fact or predict any future event?",
    "Would you rather have a lifetime supply of your favorite food or your favorite beverage?",
    "Would you rather be able to control gravity or control time?",
    "Would you rather be able to speak with the deceased or communicate with future generations?",
    "Would you rather have perfect health but no wealth or great wealth but poor health?",
    "Would you rather have the power to change your appearance at will or read minds?",
    "Would you rather have the ability to instantly learn any martial art or be a chess grandmaster?",
    "Would you rather be able to talk to plants and make them grow or talk to animals and understand their thoughts?",
    "Would you rather have the power to control dreams or control nightmares?",
    "Would you rather have a personal spaceship or a personal submarine?",
    "Would you rather always know when someone is lying to you or always get away with lying?",
    "Would you rather live in a world with unlimited clean energy but no internet or a world with advanced technology but limited resources?",
    "Would you rather have the ability to cure any illness or solve any environmental problem?",
    "Would you rather be a famous singer with no control over your music or a lesser-known artist with full creative control?",
    "Would you rather have the power to speak with inanimate objects or control the weather?",
    "Would you rather have the ability to understand and speak to animals or have superhuman strength?",
    "Would you rather live in a world with no pain or no fear?",
    "Would you rather have the power to make others laugh uncontrollably or make them cry tears of joy?",
    "Would you rather be able to visit any time in history or explore any place on Earth instantly?",
    "Would you rather have the power of flight but only at night or the power of invisibility but only in the daytime?",
    "Would you rather always know the right thing to say or have the ability to make everyone laugh at your jokes?",
    "Would you rather have a photographic memory or the ability to see into the future?",
    "Would you rather be able to speak to the entire world at once or understand the thoughts of everyone around you?"
]

currency_codes = [
    "USD",
    "EUR",
    "GBP",
    "JPY",
    "CAD",
    "AUD",
    "CHF",
    "CNY",
    "INR",
    "BRL",
    "ZAR",
    "MXN",
    "SGD",
    "NZD",
    "HKD",
    "RUB",
    "KRW",
    "SAR",
    "AED",
    "SEK",
    "NOK",
    "DKK",
    "JPY",
    "THB",
    "MYR",
    "IDR",
    "PHP",
    "TRY",
    "EGP",
    "ARS",
    "CLP",
    "COP",
    "VEF",
    "NGN",
    "ZMW",
    "KES",
    "GHS",
    "AED",
    "QAR",
    "OMR",
    "KWD",
    "BHD",
    "RSD",
    "UAH",
    "PLN",
    "HUF",
    "CZK",
    "SGD",
    "NZD",
    "HKD",
    "KRW",
    "AED",
    "SAR",
    "EGP",
    "ILS",
    "QAR",
    "OMR",
    "KWD",
]
